# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Les Rôlistes de la Pointe
email: rolistesdelapointe@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rolistesdelapointe.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "_posts/pages_blog/*"
    values:
      permalink: /blog/:title
      layout: page
      type: blog
  -
    scope:
      path: "_posts/pages_infos/*"
    values:
      permalink: /infos-pratiques/:title
      layout: page
      type: info
  -
    scope:
      path: "_posts/contenus_home/*"
    values:
      type: home
  -
    scope:
      path: "pages/*"
    values:
      layout: page
      type: page
